config/routes.rb
Rails.application.routes.draw do

  resources :shop_attachments
  get 'clubs/index', as: :clubs
  post 'clubs/talk' => 'clubs#talk'
  get 'clubs/update/:id' => 'clubs#update'
  get 'clubs/page' => 'clubs#page', as: :club_page

  get 'shops/city' => 'shops#region'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :shops do
    collection do
      get '/page' => 'shops#page', as: :shop_page
    end

    member do
      post 'review'
    end
  end

  resources :escapes do
    collection do
      get 'page' => 'escapes#page', as: :escape_page

      post '/:escape_id/comments' => 'escapes#create_comment', as: :create_comment_to
      delete '/:escape_id/comments/:comment_id' => 'escapes#delete_comment', as: :delete_comment_to
      patch '/:escape_id/comments/:comment_id' => 'escapes#update_comment', as: :update_comment_to

      get '/:escape_id/join' => 'escapes#join_escape'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
 }

  root 'home#index'

  get 'home/index'

end

app/models/shop_attachment.rb
class ShopAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :shop
end

app/controllers/shop_attachments_controller.rb
class ShopAttachmentsController < InheritedResources::Base
  load_and_authorize_resource

  def update
    @shop_attachment = Shop_attachment.find(params[:id])
    respond_to do |format|
      if @shop_attachment.update(shop_attachment_params)
        format.html { redirect_to @shop_attachment.post, notice: 'Shop attachment was successfully updated.' }
      end
    end
  end

  private

    def shop_attachment_params
      params.require(:shop_attachment).permit(:shop_id, :avatar)
    end
end

app/helpers/shop_attachments_helper.rb
module ShopAttachmentsHelper
end

app/views/shop_attachments/_form.html.erb
<%= image_tag @shop_attachment.avatar %>
<%= form_for(@shop_attachment) do |f| %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_attachments/edit.html.erb
<h1>Editing Shop Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_attachment %> |
<%= link_to 'Back', shop_attachments_path %>

app/views/shop_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shop Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Shop</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_attachments.each do |shop_attachment| %>
      <tr>
        <td><%= shop_attachment.shop_id %></td>
        <td><%= shop_attachment.avatar %></td>
        <td><%= link_to 'Show', shop_attachment %></td>
        <td><%= link_to 'Edit', edit_shop_attachment_path(shop_attachment) %></td>
        <td><%= link_to 'Destroy', shop_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop attachment', new_shop_attachment_path %>

app/views/shop_attachments/new.html.erb
<h1>New Shop Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_attachments_path %>

app/views/shop_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop:</strong>
  <%= @shop_attachment.shop_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @shop_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_shop_attachment_path(@shop_attachment) %> |
<%= link_to 'Back', shop_attachments_path %>