config/routes.rb
Rails.application.routes.draw do

  resources :shop_attachments
  get 'clubs/index', as: :clubs
  post 'clubs/talk' => 'clubs#talk'
  get 'clubs/update/:id' => 'clubs#update'
  get 'clubs/page' => 'clubs#page', as: :club_page

  get 'shops/city' => 'shops#region'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :shops do
    collection do
      get '/page' => 'shops#page', as: :shop_page
    end

    member do
      post 'review'
    end
  end

  resources :escapes do
    collection do
      get 'page' => 'escapes#page', as: :escape_page

      post '/:escape_id/comments' => 'escapes#create_comment', as: :create_comment_to
      delete '/:escape_id/comments/:comment_id' => 'escapes#delete_comment', as: :delete_comment_to
      patch '/:escape_id/comments/:comment_id' => 'escapes#update_comment', as: :update_comment_to

      get '/:escape_id/join' => 'escapes#join_escape'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
 }

  root 'home#index'

  get 'home/index'

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  resourcify

  paginates_per 5
  has_many :shop_attachments
  has_many :shop_reviews

  accepts_nested_attributes_for :shop_attachments, allow_destroy: true

  before_save {self.title = title.strip}
  validates :title, presence: true, length: {minimum: 2, maximum: 200}
  validates :content, presence: true, length: {minimum: 2, maximum: 5000}
  validates :region, presence: true

  def avg
    (self.shop_reviews.count == 0) ? 0 : self.shop_reviews.average(:rating).round(1).to_i
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :page, :region]
  load_and_authorize_resource

  def page
    if !(params[:region] == "") && !(params[:region] == "전체")
      @shop = Shop.where(region: params[:region]).order("created_at DESC").page(params[:page])
    else
      @shop = Shop.order("created_at DESC").page(params[:page])
    end
  end

  def review
    if ShopReview.where(shop_id: params[:id], user_id: current_user.id).first.nil?
      @review = ShopReview.new(
        rating: params[:rating],
        comment: params[:comment],
        user_id: current_user.id,
        shop_id: params[:id]
      )
      @flag = true if @review.save
    else
      @flag = false
    end
    # redirect_to :back
  end

  def region
    @region = params[:region]
    @shop = Shop.where(region: params[:region]).order("created_at DESC").page(params[:page])
    @shop = Shop.all.order("created_at DESC").page(params[:page]) if params[:region] == "전체"
    render 'index'
  end
  # GET /shops
  # GET /shops.json
  def index
    @shop = Shop.order("created_at DESC").page(params[:page])
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop_attachment = @shop.shop_attachments.all
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @shop_attachment = @shop.shop_attachments.build
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        unless params[:shop_attachments].nil?
          params[:shop_attachments]['avatar'].each do |a|
            @shop_attachment = @shop.shop_attachments.create!(avatar: a)
          end
        end
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        unless params[:shop_attachments].nil?
          @shop.shop_attachments.each(&:destroy) if @shop.shop_attachments.present?
          params[:shop_attachments]['avatar'].each do |a|
            @shop_attachment = @shop.shop_attachments.create!(avatar: a)
          end
        end
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:title, :content, :region, :address, shop_attachments_attributes: [:id, :shop_id, :avatar])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <div class="col-md-3 col-sm-3">
      <%= f.label :title %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <%#= f.fields_for :shop_attachments do |p| %>
    <div class="field row">
      <div class="col-md-3 col-sm-3">
        <label>사진</label>
      </div>
      <div class="col-md-6 col-sm-6">
      <!-- custom file upload -->
        <%= f.file_field :avatar, multiple: true, name: "shop_attachments[avatar][]", class: "custom-file-upload", data: {'btn_text' => 'Select a File'} %>
        <!-- <input class="custom-file-upload" multiple="multiple" type="file" id="shop_avatar" name="shop_attachments[avatar][]" data-btn-text="Select a File" /> -->
        <small class="text-muted block">Max file size: 10Mb (jpg/png) 수정시 파일을 하나라도 올리면 기존 이미지는 삭제됩니다.</small>
      </div>
    </div>
  <%# end %>

  <div class="field row">
    <div class="col-md-3 col-sm-3">
      <%= f.label :address %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="field row">
    <div class="col-md-3 col-sm-3">
      <%= f.label :region %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= select(:shop, :region, [['홍대', "홍대"], ['신촌', "신촌"], ['건대', "건대"], ['강남', "강남"], ['대학로', "대학로"]]) %>
    </div>
  </div>

  <div class="field row">
    <div class="col-md-3 col-sm-3">
      <%= f.label :content %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= f.text_area :content, maxlength: "5000", rows: 5, class: "form-control", style: "height: 200px;" %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 text-right">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop, class: "btn btn-default" %> |
<%= link_to 'Back', shops_path, class: "btn btn-default" %>

app/views/shops/index.html.erb
<!-- FEATURED -->
<section class="alternate">
  <div class="container">

    <header class="text-center mb-60">
      <h2 class="fs-25">Listing Shops</h2>
      <p class="fw-300">#홍대 #신촌 #강남 #건대 #대학로</p>
    </header>

    <div class="row property-item-list">
      <div class="col-xs-12 col-sm-6">
        <div class="property-item property-item-box">
          <!-- LEFT COLUMN -->
          <div class="col-xs-12 order-lg-1 order-md-1 mb-0">

            <div class="restate-box-search p-20">

              <h2 class="restate-box-title mb-30 block">
                <i class="fa fa-search text-silver"></i> &nbsp;
                LOCATION SEARCH
              </h2>

              <form class="m-0" action="/shops/city" method="get">


                <div class="row">

                  <div class="col-md-12">
                    <input type="hidden" id="region" value="<%= @region %>">
                    <select class="form-control select2" name="region">
                      <option value="" disabled="disabled">Please, select a city.</option>
                      <option value="전체">전체</option>
                      <option value="홍대">홍대</option>
                      <option value="신촌">신촌</option>
                      <option value="강남">강남</option>
                      <option value="건대">건대</option>
                      <option value="대학로">대학로</option>
                      <!-- <option value="5">The Hamptons</option>
                      <option value="6">Los Angeles &amp; Orange County</option>
                      <option value="7">Santa Barbara &amp; Montecito</option>
                      <option value="8">Aspen</option>
                      <option value="9">San Francisco Bay Area</option> -->
                    </select>

                  </div>

                </div>



                <div class="row">
                  <div class="col-md-12">

                    <div class="">

                        <button class="btn btn-primary" type="submit">GO</button>

                    </div>

                  </div>
                </div>

              </form>


            </div>

          </div>
        </div>
      </div>
      <% @shop.each do |shop| %>
        <div class="col-xs-12 col-sm-6">
          <div class="property-item property-item-box">
            <!-- IMAGE -->
            <a class="property-image" href="/shops/<%= shop.id %>">
              <% if shop.shop_attachments.first.nil? %>
                <img class="img-fluid" src="http://placehold.it/200x100">
              <% else %>
                <img class="img-fluid" src="<%= shop.shop_attachments.first.avatar.thumb %>" alt="해당 카페는 이미지가 없습니다.">
              <% end %>
            </a>
            <!-- PRICE and STREET LOCATION -->
            <h4 class="property-item-price">
              <!-- <strong class="text-primary">
                $1,595,000

              </strong> -->
              <small class="float-right text-danger">
                <%= shop.region %>
              </small>
            </h4>

            <!-- DETAILED LOCATION -->
            <strong class="poperty-item-location fs-16 text-black">
              <%= shop.title %>
            </strong>

            <!-- FEATURES -->
            <ul class="property-item-features list-inline mb-0">
                <li>#방탈출</li>

                <li style="list-style: none">|</li>

                <li>#테마</li>

                <li style="list-style: none">|</li>

                <li>#지역</li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>

    <div class="text-center mt-30">

      <a href="#" class="btn btn-primary bg-black border-black more">더보기</a>

    </div>

  </div>
      </section>
      <!-- /FEATURED -->

<br>

<%= link_to 'New Shop', new_shop_path, class: "btn btn-black" if can? :create, Shop %>

<% content_for :script do %>
  <script>
    $(document).ready(function() {
      var page_count = 2;
      var region = $('#region').val();
      $('.more').on('click', function(e) {
        e.preventDefault();
        $.ajax({
          url: '/shops/page',
          method: 'GET',
          data: {
            page: page_count++,
            region: region
          }
        })
      })
    })
  </script>

<% end %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path, class: "btn btn-default" %>

app/views/shops/page.js.erb
if(<%= @shop.first.nil? %>)
  alert("마지막 페이지 입니다.");
else
$('.property-item-list').append(`
  <% @shop.each do |shop| %>
    <div class="col-xs-12 col-sm-6">
      <div class="property-item property-item-box">
        <!-- IMAGE -->
        <a class="property-image" href="/shops/<%= shop.id %>">
          <% if shop.shop_attachments.first.nil? %>
            <img class="img-fluid" src="http://placehold.it/200x100">
          <% else %>
            <img class="img-fluid" src="<%= shop.shop_attachments.first.avatar.thumb %>" alt="해당 카페는 이미지가 없습니다.">
          <% end %>
        </a>

        <!-- PRICE and STREET LOCATION -->
        <h4 class="property-item-price">

          <small class="float-right text-danger">
            <%= shop.region %>
          </small>
        </h4>

        <!-- DETAILED LOCATION -->
        <strong class="poperty-item-location fs-16 text-black">
          <%= shop.title %>
        </strong>

        <!-- FEATURES -->
        <ul class="property-item-features list-inline mb-0">
            <li>#방탈출</li>

            <li style="list-style: none">|</li>

            <li>#테마</li>

            <li style="list-style: none">|</li>

            <li>#지역</li>
        </ul>
      </div>
    </div>
  <% end %>
`)

app/views/shops/review.js.erb
<% if @flag %>
  $('.comment-list').prepend(`
    <div class="row">
      <div class="col-md-10 col-sm-10">
        <div class="card card-default">
          <div class="card-block">
            <header class="text-left">
              <span class="comment-user"><i class="fa fa-user"></i> <%= @review.user.nickname %></span>
            </header>
            <header class="text-right">
              <span class="comment-date"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(@review.created_at) %></span>
            </header>
            <strong>별점 : </strong><span class="rating rating-<%= @review.rating %> fs-15 text-warning"><!-- rating-1 ... rating-5 --></span>
            <div class="comment-post">
              <p>
                <%= @review.comment %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    `);
    $('#review').val('');
    alert("리뷰가 성공적으로 등록되었습니다.")
<% else %>
  alert("이미 작성하신 리뷰가 있습니다.")
<% end %>

app/views/shops/show.html.erb
	<!-- SLIDER -->
	<section id="slider">
		<% if @shop_attachment.first.nil? %>
			<img src="http://placehold.it/1200x800"  class="imgLoaded" data-alignment="" data-portrait="" width="1200" height="800" style="visibility: visible;">
		<% else %>
			<img src="<%= @shop_attachment.first.avatar %>"  class="imgLoaded" data-alignment="" data-portrait="" width="1200" height="800" style="visibility: visible;">
		<% end %>
		<!-- ribbon -->
		<!-- <div class="property-ribbon">
			<span class="bg-red text-white">SALE</span>
			<span class="bg-blue text-white">-10% OFF</span>
		</div> -->
		<!-- /ribbon -->

	</section>
	<!-- /SLIDER -->



	<!-- PROPERTY PRICE/INFO -->
	<section class="page-header page-header-xs light">
		<div class="container">

			<div class="row">

				<div class="col-md-6">

					<span class="restate-item restate-item-price text-center">
						<!-- 14,000 원<i class="text-muted restate-monthly fs-12"> /1인</i> -->
						<!-- <a href="#mortgage-calculator" data-toggle="collapse" class="fs-11">MORTGAGE CALCULATOR</a> -->
						<!--<span class="text-muted fs-11">MONTHLY PRICE</span>-->
					</span>

					<span class="restate-item text-center">
						<!-- 5
						<span class="text-muted fs-11">ROOMS</span> -->
					</span>

					<span class="restate-item text-center">
						<!-- 8
						<span class="text-muted fs-11">Episode</span> -->
					</span>

				</div>


				<div class="col-md-6 restate-item-buttons m-0-xs">

					<!--
						+ FULLSCREEN GOOGLE MAP
							data-lat  = google map latitude
							data-lng  = google map longitude
							* used by: assets/js/view/pack_realestate.js
					-->
					<a target="_blank" href='https://map.naver.com/index.nhn?query=<%= "#{@shop.address}" %>' class="btn btn-default btn-sm m-0">
						<i class="fa fa-map-o"></i>
						FULLSCREEN MAP
					</a>

				</div>

			</div>

		</div>
	</section>
	<!-- PROPERTY PRICE/INFO -->


	<!-- PROPERTY DETAILS -->
	<section>
		<div class="container">

			<h2 class="fs-20 mb-20 fw-800">
				<span class="text-muted fw-300" title="property unique id">Room Escafe Cafe <%= @shop.id %></span> <%= @shop.title %>
				<% if @shop.avg == 0 %>
					<span class="rating fs-15 text-warning">평가없음</span>
				<% else %>
					<span class="rating rating-<%= @shop.avg %> fs-15 text-warning"><!-- rating-1 ... rating-5 --></span>
				<% end %>
			</h2>

			<div class="row">

				<div class="col-sm-8">

					<div class="text-black"><span class="text-muted">Location:</span>  <%= @shop.address %> </div>
					<!-- <div class="text-black"><span class="text-muted">Price:</span>  40,000 <span class="text-muted fs-11">/ ROOM</span></div> -->
					<!-- <div class="text-black"><span class="text-muted">Minimum Down Payment:</span>  15%</div> -->

				</div>

				<!-- <div class="col-sm-4">

					<div class="text-black"><span class="text-muted">Type:</span>  Crime Scene</div>
					<div class="text-black"><span class="text-muted">Business Hours:</span>  9:00am - 10:00pm</div>

				</div> -->

				<!-- <div class="col-sm-4">

					<div class="text-black"><span class="text-muted">Units in Building:</span>  78</div>
					<div class="text-black"><span class="text-muted">Building Type:</span>  Highrise</div>
					<div class="text-black"><span class="text-muted">Floor:</span>  11</div>

				</div> -->

			</div>


		</div>
	</section>
	<!-- /PROPERTY DETAILS -->



	<!-- PROPERTY DESCRIPTION -->
	<section>
		<div class="container">

			<!-- <h2 class="fs-20 fw-800">
				<span class="text-muted fw-300" title="property unique id">RE001</span> PROPERTY DESCRIPTION
			</h2> -->


			<div class="row">

				<div class="col-sm-8">
					<p><%= simple_format(@shop.content) %></p>
				</div>

				<div class="col-sm-4 m-0-xs">
					<h3 class="fs-16 fw-800">PROPERTY IMAGES</h3>

					<div class="row lightbox" data-plugin-options='{"delegate": "a", "gallery": {"enabled": true}}'>

						<% @shop_attachment.each do |p| %>
							<div class="col-xs-6 col-md-6 col-lg-6 mb-30">
								<a href="<%= p.avatar %>" class="image-hover-plus image-hover-overlay">
									<i class="icon-hover-plus"></i>
									<img class="img-fluid" src=" <%= p.avatar.thumb %> " alt="">
								</a>
							</div>
						<% end %>

						<!-- <div class="col-xs-6 col-md-6 col-lg-6 mb-30">
							<a href="<%#= @shop.avatar.thumb %>" class="image-hover-plus image-hover-overlay">
								<i class="icon-hover-plus"></i>
								<img class="img-fluid" src="<%#= @shop.avatar.thumb %>" alt="">
							</a>
						</div> -->

						<!-- <div class="col-xs-6 col-md-6 col-lg-6 mb-30">
							<a href="demo_files/images/packs/realestate/gallery-item/5-min.jpg" class="image-hover-plus image-hover-overlay">
								<i class="icon-hover-plus"></i>
								<img class="img-fluid" src="demo_files/images/packs/realestate/gallery-item/5-min.jpg" alt="">
							</a>
						</div>

						<div class="col-xs-6 col-md-6 col-lg-6 mb-30">
							<a href="demo_files/images/packs/realestate/gallery-item/3-min.jpg" class="image-hover-plus image-hover-overlay">
								<i class="icon-hover-plus"></i>
								<img class="img-fluid" src="demo_files/images/packs/realestate/gallery-item/3-min.jpg" alt="">
							</a>
						</div> -->

					</div>


					<div class="row restate-item-buttons m-0-xs">

						<div class="col-md-6 mb-10">

							<!--
								+ FULLSCREEN GOOGLE MAP
									data-lat  = google map latitude
									data-lng  = google map longitude
									* used by: assets/js/view/pack_realestate.js
							-->
							<a target="_blank" href='https://map.naver.com/index.nhn?query=<%= "#{@shop.address}" %>' class="btn btn-default btn-block  m-0">
								<i class="fa fa-map-o"></i>
								MAP
							</a>

						</div>

						<div class="col-md-6 mb-10">

							<!-- FLOOR PLAN -->
							<!-- <a href="demo_files/images/packs/realestate/floorplan.jpg" class="btn btn-default btn-block m-0 lightbox" data-plugin-options='{"type":"image"}'>
								<i class="fa fa-university"></i>
								FLOORPLAN
							</a> -->

						</div>

					</div>

				</div>

			</div>


		</div>
	</section>
	<!-- /PROPERTY DESCRIPTION -->

	<!-- Form -->
	<%= form_tag("/shops/#{@shop.id}/review", method: :post) do %>
	  <div class="row">
	    <div class="col-md-8">
        <label>평점 : <%= select_tag :rating, "<option>5</option><option>4</option><option>3</option><option>2</option><option>1</option>".html_safe %> <br>
				</label>
				<label>리뷰:</label>
				<%= text_field_tag :comment, nil, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<button id="shopreview" class="btn btn-3d btn-lg btn-reveal btn-black">
					<i class="fa fa-check"></i>
					<span>SUBMIT REVIEW</span>
				</button>
			</div>
		</div>
	<% end %>
  <!-- /Form -->

	<!-- Comment -->
	<div class="comment-list">
    <% @shop.shop_reviews.reverse.each do |review| %>
			<div class="row">
				<div class="col-md-10 col-sm-10">
					<div class="card card-default">
						<div class="card-block">
							<header class="text-left">
								<span class="comment-user"><i class="fa fa-user"></i> <%= review.user.nickname %></span>
							</header>
							<header class="text-right">
								<span class="comment-date"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(review.created_at) %></span>
							</header>
							<strong>별점 : </strong><span class="rating rating-<%= review.rating %> fs-15 text-warning"><!-- rating-1 ... rating-5 --></span>
							<div class="comment-post">
								<br>
								<p>
									<%= review.comment %>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
    <% end %>
	</div>

<header class="text-center">
	<%= link_to 'Edit', edit_shop_path(@shop), class: "btn btn-default btn-3d btn-lg btn-reveal" if can? :edit, @shop%>
	<%= link_to 'Back', shops_path, class: "btn btn-default btn-3d btn-lg btn-reveal" %>
</header>

<% content_for :script do %>
	<script>
		$(function(){
			$('#shopreview').on('click', function(e) {
				e.preventDefault();
				var comment = $('#comment').val();
				var rating = $('#rating').val();
				if('<%= current_user %>'){
					if (!(comment.trim().length < 1) && !(comment.length > 255)){
						$.ajax({
							url: '/shops/<%= @shop.id %>/review',
							method: "POST",
							data: {
								comment: comment,
								rating: rating
							},
							headers: {
								'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
							}
						});
					}else
						alert("2글자 이상 255자까지 작성 가능합니다.");
				}else
					alert("로그인해야 작성 가능합니다.");
			})
		})
	</script>
<% end %>