config/routes.rb
Rails.application.routes.draw do

  resources :shop_attachments
  get 'clubs/index', as: :clubs
  post 'clubs/talk' => 'clubs#talk'
  get 'clubs/update/:id' => 'clubs#update'
  get 'clubs/page' => 'clubs#page', as: :club_page

  get 'shops/city' => 'shops#region'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :shops do
    collection do
      get '/page' => 'shops#page', as: :shop_page
    end

    member do
      post 'review'
    end
  end

  resources :escapes do
    collection do
      get 'page' => 'escapes#page', as: :escape_page

      post '/:escape_id/comments' => 'escapes#create_comment', as: :create_comment_to
      delete '/:escape_id/comments/:comment_id' => 'escapes#delete_comment', as: :delete_comment_to
      patch '/:escape_id/comments/:comment_id' => 'escapes#update_comment', as: :update_comment_to

      get '/:escape_id/join' => 'escapes#join_escape'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
 }

  root 'home#index'

  get 'home/index'

end

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer id="footer" class="footer-light">
  <div class="copyright has-social">
    <div class="container">

        <!-- Social Icons -->
  			<div class="float-right">
  				<a href="https://www.facebook.com/%EC%9E%BC%ED%83%80%EC%BF%A0-143745799739164/" class="social-icon social-icon-sm social-icon-transparent social-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
  					<i class="icon-facebook"></i>
  					<i class="icon-facebook"></i>
  				</a>

  				<!-- <a href="https://solwish.github.io/" class="social-icon social-icon-sm social-icon-transparent social-github" data-toggle="tooltip" data-placement="top" title="Github">
  					<i class="icon-github"></i>
  					<i class="icon-github"></i>
  				</a> -->

  				<!-- <a href="#" class="social-icon social-icon-sm social-icon-transparent social-gplus" data-toggle="tooltip" data-placement="top" title="Google plus">
  					<i class="icon-gplus"></i>
  					<i class="icon-gplus"></i>
  				</a>

  				<a href="#" class="social-icon social-icon-sm social-icon-transparent social-linkedin" data-toggle="tooltip" data-placement="top" title="Linkedin">
  					<i class="icon-linkedin"></i>
  					<i class="icon-linkedin"></i>
  				</a>

  				<a href="#" class="social-icon social-icon-sm social-icon-transparent social-rss" data-toggle="tooltip" data-placement="top" title="Rss">
  					<i class="icon-rss"></i>
  					<i class="icon-rss"></i>
  				</a> -->
  			</div>
  			<!-- /Social Icons -->

      <div class="copyright-text float-left">
        &copy; All Rights Reserved, Gemtaku
      </div>
    </div>
  </div>

</footer>
<!-- /FOOTER -->


<!-- SCROLL TO TOP -->
<a href="#" id="toTop"></a>

app/views/shared/_nav.html.erb
<div id="header" class="navbar-toggleable-md clearfix header-sm sticky disable-uppercase">

<!-- TOP NAV -->
<header id="topNav">
  <div class="container">

    <!-- Mobile Menu Button -->
    <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
      <i class="fa fa-bars"></i>
    </button>



    <!-- Logo -->
    <a class="logo float-left no-text-underline" href="<%= root_path %>">
      <img src="/images/logo2.png" alt="" />
    </a>



    <!--
      Top Nav
    -->
    <div class="navbar-collapse collapse float-right nav-main-collapse p-0">
      <nav class="nav-main">

        <!--
          NOTE

          For a regular link, remove "dropdown" class from LI tag and "dropdown-toggle" class from the href.
          Direct Link Example:

          <li>
            <a href="#">HOME</a>
          </li>

          + MENU EFFECTS
            .nav-animate-fadeIn
            .nav-animate-fadeInUp
            .nav-animate-bounceIn
            .nav-animate-bounceInUp
            .nav-animate-flipInX
            .nav-animate-flipInY
            .nav-animate-zoomIn
            .nav-animate-slideInUp

            .nav-hover-animate 	= animate text on hover

        -->
        <ul id="topMain" class="nav nav-pills nav-main nav-animate-fadeIn">
          <li><!-- ABOUT -->
            <a href="<%= shops_path %>">
              방탈출 카페
            </a>
          </li>
          <li><!-- BLOG -->
            <a href="<%= escapes_path %>">
              게시판
            </a>
          </li>
          <li><!-- CONTACT -->
            <a href="<%= clubs_path %>">
              클럽
            </a>
          </li>
        </ul>

      </nav>
    </div>

  </div>
</header>
<!-- /Top Nav -->

</div>

app/views/shared/_topbar.html.erb

<!-- Top Bar -->
<div id="topBar">
  <div class="container">
    <% if user_signed_in? %>
      <!-- right -->
      <ul class="top-links list-inline float-right">
        <li class="text-welcome hidden-xs-down">Welcome to Gemtaku, <strong><%= current_user.nickname %></strong></li>
        <li>
          <a class="dropdown-toggle no-text-underline" data-toggle="dropdown" href="#"><i class="fa fa-user hidden-xs-down"></i> MY ACCOUNT</a>
          <ul class="dropdown-menu float-right">
            <li><a href="<%=edit_user_registration_path%>"><i class="fa fa-unlock-alt"></i> EDIT USER</a></li>
            <!-- <li><a href="#"><i class="fa fa-history"></i> BOOKINGS</a></li> -->
            <!-- <li class="divider"></li> -->
            <!-- <li><a href="#"><i class="fa fa-edit"></i> MY REVIEWS</a></li> -->
            <!-- <li><a href="#"><i class="fa fa-cog"></i> MY SETTINGS</a></li> -->
            <li class="divider"></li>
            <li><a href="<%= destroy_user_session_path %>" data-method="delete" data-confirm="로그아웃 하시겠습니까??"><i class="glyphicon glyphicon-off"></i> LOGOUT</a></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <ul class="top-links list-inline float-right">
        <li class="text-welcome hidden-xs-down">Welcome to Gemtaku</li>
        <li><a class="no-text-underline" href="<%= new_user_session_path %>"><i class="fa fa-user"></i> LOG IN</a></li>
        <li><a class="no-text-underline" href="<%= new_user_registration_path %>"><i class="fa fa-user-plus"></i> SIGN UP</a></li>
      </ul>
    <% end %>
  </div>
</div>
<!-- /Top Bar -->