config/routes.rb
Rails.application.routes.draw do

  resources :shop_attachments
  get 'clubs/index', as: :clubs
  post 'clubs/talk' => 'clubs#talk'
  get 'clubs/update/:id' => 'clubs#update'
  get 'clubs/page' => 'clubs#page', as: :club_page

  get 'shops/city' => 'shops#region'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :shops do
    collection do
      get '/page' => 'shops#page', as: :shop_page
    end

    member do
      post 'review'
    end
  end

  resources :escapes do
    collection do
      get 'page' => 'escapes#page', as: :escape_page

      post '/:escape_id/comments' => 'escapes#create_comment', as: :create_comment_to
      delete '/:escape_id/comments/:comment_id' => 'escapes#delete_comment', as: :delete_comment_to
      patch '/:escape_id/comments/:comment_id' => 'escapes#update_comment', as: :update_comment_to

      get '/:escape_id/join' => 'escapes#join_escape'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
 }

  root 'home#index'

  get 'home/index'

end

app/models/escape.rb
class Escape < ActiveRecord::Base
  resourcify

  belongs_to :user
  has_many :comments
  has_many :joins

  paginates_per 20
  def require_permission?(user)
    self.user.id == user.id
  end

  before_save {self.title = title.strip}
  validates :title, presence: true, length: {minimum: 2, maximum: 100}
  validates :content, presence: true, length: {minimum: 2, maximum: 2500}
end

app/controllers/escapes_controller.rb
class EscapesController < ApplicationController
  before_action :set_escape, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :page]
  load_and_authorize_resource

  def page
    @escapes = Escape.order("created_at DESC").page(params[:page]).includes(:comments)
  end

  # GET /escapes
  # GET /escapes.json
  def index
    @notices = Escape.where(is_notice: true)
    @escapes = Escape.order("created_at DESC").page(params[:page]).includes(:comments)
  end

  # GET /escapes/1
  # GET /escapes/1.json
  def show
    if user_signed_in?
      @join = Join.where(user_id: current_user.id, escape_id: params[:id])
    else
      @join = []
    end
  end

  # GET /escapes/new
  def new
    @escape = Escape.new
  end

  # GET /escapes/1/edit
  def edit
  end

  # POST /escapes
  # POST /escapes.json
  def create
    @escape = current_user.escapes.new(escape_params)

    respond_to do |format|
      if @escape.save
        format.html { redirect_to @escape, notice: 'Escape was successfully created.' }
        format.json { render :show, status: :created, location: @escape }
      else
        format.html { render :new }
        format.json { render json: @escape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escapes/1
  # PATCH/PUT /escapes/1.json
  def update
    respond_to do |format|
      if @escape.update(escape_params)
        format.html { redirect_to @escape, notice: 'Escape was successfully updated.' }
        format.json { render :show, status: :ok, location: @escape }
      else
        format.html { render :edit }
        format.json { render json: @escape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escapes/1
  # DELETE /escapes/1.json
  def destroy
    # @escape.comments.each(&:destroy)
    @escape.destroy
    respond_to do |format|
      format.html { redirect_to escapes_url, notice: 'Escape was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join_escape
    @join = Join.where(user_id: current_user.id, escape_id: params[:escape_id]).first
    unless @join.nil?
      @join.destroy
      puts '참가 취소'
    else
      @join = Join.create(user_id: current_user.id, escape_id: params[:escape_id])
      puts '참여가 완료되었습니다.'
    end
    # redirect_to :back
  end

  def create_comment
    @comment = Comment.new(user_id: current_user.id, escape_id: params[:escape_id], content: params[:content])
    @flag = false
    @flag = true if @comment.save
  end


  def  delete_comment
    @comment = Comment.find(params[:comment_id])
    @flag = false
    @flag = true if (@comment.user_id == current_user.id) && @comment.destroy
  end

  def update_comment
    @comment = Comment.find(params[:comment_id])
    @flag = false
    @flag = true if (@comment.user_id == current_user.id) && @comment.update(content: params[:content], is_edited: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escape
      @escape = Escape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def escape_params
      params.require(:escape).permit(:title, :content)
    end
end

app/helpers/escapes_helper.rb
module EscapesHelper
end

app/views/escapes/_form.html.erb
<%= form_for(@escape) do |f| %>
  <% if @escape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@escape.errors.count, "error") %> prohibited this escape from being saved:</h2>

      <ul>
      <% @escape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <div class="col-md-1 col-sm-1">
      <%= f.label :title %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= f.text_field :title, class: "form-control", maxlength: "255" %>
    </div>
  </div>
  <div class="field row">
    <div class="col-md-1 col-sm-1">
      <%= f.label :content %><br>
    </div>
    <div class="col-md-6 col-sm-6">
      <%= f.text_area :content, maxlength: "2500", rows: 5, class: "form-control", style: "height: 200px;", placeholder: "2500자 이하로 입력 가능합니다." %>
    </div>
  </div>
  <div class="actions col-md-7 col-sm-7 text-right">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/escapes/create_comment.js.erb
<% if @flag %>
  $('.comment-list').append(`
    <tr id="comment-<%= @comment.id%>">
      <td class="comment" data-id="<%= @comment.id %>"><%= @comment.content %></td>
      <td><small class="block"><%= " #{@comment.created_at.strftime('%b')} #{@comment.created_at.strftime('%d')}, #{@comment.created_at.strftime("%Y")}" %> - <%= @comment.created_at.strftime("%H:%M:%S") %></small></td>
      <td class="media-heading bold text-center"><%= @comment.user.nickname %></td>
      <td><button class="btn delete-comment btn-default" data-id="<%=@comment.id%>" data-confirm = "Are you sure?">삭제</button></td>
    </tr>
    `);
  $('#comment-input').val('');
<% else %>
  alert("댓글을 최소 1글자 이상 300 이하로 입력해야 합니다.")
<% end %>

app/views/escapes/delete_comment.js.erb
<% if @flag %>
  alert('삭제되었습니다.');
  $('#comment-<%= @comment.id %>').hide().remove();
<% else %>
  alert("본인 댓글만 삭제할 수 있습니다.")
<% end %>

app/views/escapes/edit.html.erb
<h1>Editing Escape</h1>

<%= render 'form' %>

<%= link_to 'Show', @escape, class: "btn btn-default" %> |
<%= link_to 'Back', escapes_path, class: "btn btn-default" %>

app/views/escapes/index.html.erb
<h1>Listing Escapes</h1>

<table>
  <thead>
    <tr>
      <th width="10%">글번호</th>
      <th width="60%">제목</th>
      <th width="10%">닉네임</th>
      <th width="20%">글쓴시간</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody id="escape-list">
    <% @notices.each do |notice| %>
      <tr>
        <td><br><공지></td>
        <td><br><%= link_to notice.title, notice %></td>
        <td><br><%= notice.user.nickname %></td>
        <td><br><%= notice.created_at.strftime('%a, %d %b %Y %H:%M:%S')%></td>
      </tr>
    <% end %>
    <% @escapes.each do |escape| %>
      <tr>
        <td><br><%= escape.id %></td>
        <td><br><%= link_to escape.title, escape %>  [<%= escape.comments.count %>]</td>
        <td><br><%= escape.user.nickname %></td>
        <td><br><%= escape.created_at.strftime('%a, %d %b %Y %H:%M:%S')%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<i class = "glyphicon glyphicon-pencil"></i>New Escape'.html_safe, new_escape_path, class: 'btn btn-info' %>

<% content_for :script do %>
  <%#= paginate @escapes %>
<% end %>

<% content_for :script do %>
  <script>
    $(document).ready(function() {
      var page_count = 2;
      setInterval(function() {
        if($(window).scrollTop() >= $(document).height() - $(window).height() - 1) {
          $.ajax({
            url: '/escapes/page',
            method: 'GET',
            data: {
              page: page_count++
            }
          })
        }
      }, 3000);
    })
  </script>
<% end %>

app/views/escapes/join_escape.js.erb
alert("참가버튼 누름");
$('.join').toggleClass('btn-outline-primary btn-primary');
  var join_count = parseInt($('#join-count').text());
    if(<%= @join.frozen? %>){ 
      $('#join-count').text(join_count - 1);
    } else {
      $('#join-count').text(join_count + 1);
    }

app/views/escapes/new.html.erb
<h1>New Escape</h1>

<%= render 'form' %>

<%= link_to '<i class="fa fa-home"></i>홈으로'.html_safe , escapes_path,class: 'btn btn-dark'%>

app/views/escapes/page.js.erb
$('#escape-list').append(`
  <% @escapes.each do |escape| %>
    <tr>
      <td><br><%= escape.id %></td>
      <td><br><%= link_to escape.title, escape %>  [<%= escape.comments.count %>]</td>
      <td><br><%= escape.user.nickname %></td>
      <td><br><%= escape.created_at.strftime('%a, %d %b %Y %H:%M:%S')%></td>
    </tr>
  <% end %>
`)

app/views/escapes/show.html.erb
<div class="row">

	<!-- LEFT -->
	<div class="col-md-9 col-sm-9">

		<h1 class="blog-post-title"> <%= @escape.title %> </h1>
		<ul class="blog-post-info list-inline">
			<li>
				<a href="#">
					<i class="fa fa-clock-o"></i>
					<span class="font-lato"><%= " #{@escape.created_at.strftime('%b')} #{@escape.created_at.strftime('%d')}, #{@escape.created_at.strftime("%Y")}" %></span>
				</a>
			</li>
			<li>
				<a href="#">
					<i class="fa fa-comment-o"></i>
					<span class="font-lato"><%= @escape.comments.count %> Comments</span>
				</a>
			</li>
			<li>
				<a href="#">
					<i class="fa fa-user"></i>
					<span class="font-lato"><%= @escape.user.nickname %></span>
				</a>
			</li>
		</ul>

		<!-- article content -->
		<p><%= simple_format(@escape.content) %></p>
		<!-- /article content -->
		<% if @join.length > 0 %>
	    <button type="button" class="join btn btn-3d btn-lg btn-reveal btn-black" >참여취소 <span id ="join-count"><%= @escape.joins.count %></span></button>
	  <% else %>
	    <button type="button" class="join btn btn-3d btn-lg btn-reveal btn-black" >참여하기 <span id ="join-count"><%= @escape.joins.count %></span></button>
	  <% end %>
		<div class="text-right">
			<% if user_signed_in? && @escape.require_permission?(current_user) %>
				<td><%= link_to "수정하기", edit_escape_path(@escape), class: "btn btn-3d btn-lg btn-reveal btn-secondary" %></td>
				<td><%= link_to "삭제하기", @escape, data: {method: :delete, confirm: 'Are you sure?' }, class: "btn btn-3d btn-lg btn-reveal btn-secondary" %></td>
			<% end %>
		</div>
		<div class="text-right">
			<%= link_to 'Back', escapes_path, class: "btn btn-3d btn-lg btn-reveal btn-default" %>
		</div>
		<!-- COMMENTS -->
		<div id="comments" class="comments">

			<h4 class="page-header mb-60 fs-20">
				<span><%= @escape.comments.count %></span> COMMENTS
			</h4>

			<!-- comment item -->
			<table>
				<thead>
					<tr>
						<th width="60%">내용</th>
						<th width="15%"></th>
						<th width="10%"></th>
						<th width="15%"></th>
					</tr>
				</thead>
				<tbody class="comment-list">
					<% @escape.comments.each do |comment| %>
					<tr id="comment-<%= comment.id %>">
						<td class="comment" data-id="<%= comment.id %>"><%= comment.content%></td>
						<% if comment.is_edited %>
							<td><small class="block"><%= " #{comment.updated_at.strftime('%b')} #{comment.updated_at.strftime('%d')}, #{comment.updated_at.strftime("%Y")}" %> - <%= comment.updated_at.strftime("%H:%M:%S") %><br>Edited</small></td>
						<% else %>
							<td><small class="block"><%= " #{comment.created_at.strftime('%b')} #{comment.created_at.strftime('%d')}, #{comment.created_at.strftime("%Y")}" %> - <%= comment.created_at.strftime("%H:%M:%S") %></small></td>
						<% end %>
						<td class="media-heading bold text-center"><%= comment.user.nickname %></td>
						<td><button class="btn delete-comment btn-default" data-id="<%= comment.id %>" data-confirm = "Are you sure?">삭제</button></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<% if current_user %>
			<!-- Form -->
			<form id="comment-form">
				<div class="row">
					<div class="col-md-12">
						<label>COMMENT</label>
						<textarea required="required" maxlength="5000" rows="5" class="form-control" name="comment" id="comment-input"></textarea>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">

						<button class="btn btn-3d btn-lg btn-reveal btn-black">
							<i class="fa fa-check"></i>
							<span>LEAVE A COMMENT</span>
						</button>

					</div>
				</div>

			</form>
			<!-- /Form -->
			<% else %>
				<p>로그인해야 댓글을 달 수 있습니다.</p>
			<% end %>

		</div>
		<!-- /COMMENTS -->


	</div>

</div>

  <% content_for :script do %>
    <script>
      $(function(){
        $('.join').on('click', function(){
          $.ajax({
            url: "/escapes/<%= @escape.id %>/join",
            method: "GET"
          });
        });
        //댓글작성하기
        $('#comment-form').on('submit', function(e){
          e.preventDefault();
          var data = $('#comment-input').val();
          if('<%= current_user %>'){
            $.ajax({
              url: '/escapes/<%= @escape.id %>/comments',
              method: 'POST',
              data: {
                content: data
              },
              headers: {
                // 'X-Transaction': 'POST Example',
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
              }
            });
          }else
            alert("로그인을 해주세요.")
        });
        //댓글삭제하기
        $('.comment-list').on('click', '.delete-comment', function(){
          var id = $(this).data('id');
          if('<%= current_user %>'){
            $.ajax({
              url: '/escapes/<%= @escape.id %>/comments/' + id,
              method: "DELETE",
              headers: {
                // 'X-Transaction': 'POST Example',
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
              }
            });
          }else
            alert("로그인을 해주세요.")
        });
        //댓글수정하기
				var text
				var nickname
        // $('.comment-list').on('click','.comment', function(){
        //   nickname = $('.text-welcome')[0].children[0].innerHTML;
        //   if(nickname == $(this).siblings()[1].innerHTML){
        //     if ($(this).parents('.comment-list').find('.comment-form').length >0){
        //         alert('이미 수정중인 comment가 있습니다');
        //         return false;
        //     }
        //     text = $(this).text();
        //     var id = $(this).data('id');
        //     $(this).siblings()[0].innerHTML = '<button class="btn btn-outline-success my-2 my-sm-0 update-comment" type="submit">수정완료</button>';
        //     $(this).replaceWith(`<td class="edit-comment"><input class="form-control comment-form" value="${text}"><input class="comment-id" type="hidden" value="${id}"></td>`);
				// 	}else
        //     alert("본인만 수정 가능합니다.");
        // });
        $('.comment-list').on('click', '.update-comment', function(){
          if('<%= current_user %>'){
            var updatedcontent = $('.comment-form').val();
            var id = $('.comment-id').val();
						if(text != updatedcontent){
	            $.ajax({
	              url: '/escapes/<%= @escape.id %>/comments/' + id,
	              method : 'PATCH',
	              data: {
	                content: updatedcontent
	              },
	              headers: {
	                // 'X-Transaction': 'POST Example',
	                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
	              }
	            })
						}else {
							alert("수정된 내용이 없습니다.")
							$(this).parent().parent().replaceWith(`<tr><td class="comment" data-id="${id}">${text}</td><td></td><td class="media-heading bold text-center">${nickname}</td><td><button class="btn delete-comment btn-default" data-id="${id}" data-confirm = "Are you sure?">삭제</button></td></tr>`);
						}
          }else
            alert("로그인을 해주세요.")
        });
      })
    </script>
  <% end %>

app/views/escapes/update_comment.js.erb
<% if @flag %>
  alert('댓글수정완료');
  $('.edit-comment').replaceWith(`<td class="comment" data-id="<%= @comment.id %>"><%= @comment.content%></td>`);
  //3. 완료버튼 삭제
  // $('.update-comment').remove();
  $('.update-comment').replaceWith('<td>	Edited	</td>');
<% else %>
  alert("댓글을 최소 1글자 이상 300 이하로 입력해야 합니다.")
<% end %>